[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang.cmd"
ar = "arm-linux-androideabi-ar"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang.cmd"
ar = "aarch64-linux-android-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang.cmd"
ar = "x86_64-linux-android-ar"