[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang.cmd"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang.cmd"

[target.i686-linux-android]
linker = "i686-linux-android-clang.cmd"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang.cmd"