[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["dylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "postgres" ] }
lazy_static = "1.4.0"
async-trait = "0.1.51"

[build-dependencies]
cargo-lipo = "3.1.1"

###########
# ANDROID #
###########

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19", default-features = false }