[package]
name = "db_explorer_shared"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["dylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
# Offline gives us the ability to serialize pg type info, so we can extract the oid.
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "postgres", "offline" ] }
lazy_static = "1.4.0"
async-trait = "0.1.51"
futures-util = "0.3"
strum = "0.21.0"
strum_macros = "0.21.1"
futures = "0.3"
backtrace = "0.3"

[build-dependencies]
cargo-lipo = "3.1.1"

###########
# ANDROID #
###########

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19", default-features = false }